### ISSUE TITLE
Error during - pip install . - 

### ISSUE THREAD

**Issue by dellamuradario** [intel/neural-speed#111]
Hi all,

I'm trying to install neural-speed library. I'm following this tutorial Build Python package (Recommended way) [](https://github.com/intel/neural-speed#installation).

System configuration:
OS : WSL2 - Linux DESKTOP-PNBMAG8 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Python: Python 3.10.12

My steps:

1.  CREATE PROJECT FOLDER: neural-speed-tutorial
2. CREATE VIRTUAL ENV: python3 -m venv neural-speed-env
3. CLONE NEURAL-SPEED REPOSITOTY: git clone https://github.com/intel/neural-speed.git
4. RUN: pip install -r requirements.txt (successful)
5. pip install .

TERMINAL LOG ERROR:
`
CMake Error in neural_speed/application/CMakeLists.txt:
        Imported target "pybind11::module" includes non-existent path
 
          "/usr/include/python3.10"
 
        in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
 
        * The path was deleted, renamed, or moved to another location.
 
        * An install or uninstall procedure did not complete successfully.
 
        * The installation package was faulty and references files it does not
        provide.
`
        
        
 What could be the solution? Did I miss any crucial steps during the installation or while executing the commands listed above?

Thank you for any suggestions.

**Comment by intellinjun** [comment]
You can use python setup.py install to see if it will give you an error?

**Comment by dellamuradario** [comment]
Hi @intellinjun thanks for your reply. I tried to use python3 setup.py and I got this error:

`
/home/dario-reply/neural-speed-tutorial/neural-speed-env/lib/python3.10/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
`
