### ISSUE TITLE
What is the difference between ITREX and Neural Speed?

### ISSUE THREAD

**Issue by jeremyfowers** [intel/neural-speed#155]
Hi, I have been reading the blog and documentation here to try and understand the pros and cons of the transformers-like usage vs. the llama.cpp-like usage. And then how those things compare to ITREX.

I am confused because the transformers-like usage of Neural Speed only calls ITREX APIs and does not call any APIs from this repo. How does the transformers-like usage actually invoke Neural Speed?

Is the llama.cpp-like usage mainly a front-end for ITREX? Should I expect to see any performance differences if I opt to use ITREX instead of the llama.cpp-like usage?

Thanks in advance for helping my understanding.

**Comment by kevinintel** [comment]
Hi,
NeuralSpeed is in ITREX before v1.3.1, ITREX use NeuralSpeed as dependency now.
You can directly use llama.cpp-like usage in NeuralSpeed  or use Transformer-like in ITREX.
We integrate Neural Speed in ITREX Transformer-like API.
There are no performance difference in the 2 usage, you can use ITREX if you like  Transformer-like  API or NeuralSpeed  if you like  llama-cpp usage.

**Comment by jeremyfowers** [comment]
Thanks @kevinintel for the fast and clear answer! If I may ask you another question, how do you see the use cases for ITREX vs. IPEX.llm? They seem like they are getting a pretty similar feature set.

**Comment by kevinintel** [comment]
Depends on the backend, ITREX provides different backends such as NeuralSpeed and ipex. If you use NeuralSpeed as backend, it's not similar to IPEX.llm.
