### ISSUE TITLE
Issue in whisper inference from pre-converted gguf

### ISSUE THREAD

**Issue by bil-ash** [intel/neural-speed#203]
I get the following error when running whisper from already converted(to gguf) whisper model (i.e, using init_from_bin instead of init)-
`Traceback (most recent call last):
  File "/root/ne/scripts/whisper_example.py", line 78, in <module>
    main()
  File "/root/ne/scripts/whisper_example.py", line 72, in main
    model.init_from_bin(args.model_name, gguf_path)
  File "/usr/local/lib/python3.11/dist-packages/neural_speed/__init__.py", line 297, in init_from_bin
    self.model.init_model(model_path, **_filter_model_args(valid_args, **generate_kwargs))
TypeError: init_model(): incompatible function arguments. The following argument types are supported:
    1. (self: neural_speed.whisper_cpp.Model, model_path: str) -> None

Invoked with: <neural_speed.whisper_cpp.Model object at 0x7f0c33157d70>, '/root/ne/scripts/ne-q40.bin'; kwargs: threads=4`

Please suggest a solution

**Comment by intellinjun** [comment]
@bil-ash  Can you use this [pr](https://github.com/intel/neural-speed/pull/218) and try again?

**Comment by bil-ash** [comment]
Works fine with mentioned PR.
