### ISSUE TITLE
Linking back to Neural Chat / intel-extension-for-transformers

### ISSUE THREAD

**Issue by thealmightygrant** [intel/neural-speed#237]
Hi y'all, I love these optimizations for inference with intel CPUs! I'm really excited to try them out as an alternative to llama.cpp that is more hightly optimized for use with Intel CPUs. 

A small suggestion: you may want to link back to the Neural Chat server in the repo somewhere so that people know that you can use neural-speed via Neural Chat. Specifically, the config [here](https://github.com/intel/intel-extension-for-transformers/blob/307c1a8bfc089e139ea29afa02ca28b05c62b988/intel_extension_for_transformers/neural_chat/server/neuralchat_server.py#L251) was not super straightforward to find if you started by looking at the docs [here](https://github.com/intel/intel-extension-for-transformers?tab=readme-ov-file#int4-inference-cpu), which leads towards the main neural-speed README. I almost fell down a rabbit hole of trying to integrate `neural-speed` with some other server framework based on the examples in the `neural-speed` repo. 😅  Also, no pressure, just a suggestion to save some pain for others.

**Comment by kevinintel** [comment]
Thanks for the suggestion, we will link it.
Btw, we are trying to integrate NeuralSpeed or kernels into other framework

**Comment by zhentaoyu** [comment]
Hi, @thealmightygrant, thanks for your advice. We have already added the doc of `Neural_Speed` usage in `Neural_Chat` (https://github.com/intel/neural-speed/pull/252). You can have a look, thanks a lot.
