### ISSUE TITLE
Build failure when building the executable

### ISSUE THREAD

**Issue by aahouzi** [intel/neural-speed#74]
### Current Behavior:

- Building the executable results in a failure, all steps are successful except the last step:

![image](https://github.com/intel/neural-speed/assets/112881240/21ce5104-36ef-4720-b656-74c77f08a585)

### Steps To Reproduce:

```
# Linux and WSL
git submodule update --init --recursive
mkdir build
cd build
cmake .. -G Ninja
ninja
```

### Environment:

- **OS:** Rocky Linux 8.8
- **HW:** Intel(R) Xeon(R) Platinum 8470Q

**Comment by VincyZhang** [comment]
Hi @aahouzi, would you please try using GCC>10?

**Comment by aahouzi** [comment]
@VincyZhang Thanks, it's working now ! Can we add this requirement somewhere before starting the build ? it would be helpful for the users..

**Comment by VincyZhang** [comment]
Thanks for reminding! Added note in Readme.md: https://github.com/intel/neural-speed/blob/5b71e268f6bb798ceb2c4609b75967ac095705ce/README.md
