### ISSUE TITLE
Low text quality when inferencing a gguf model with Neural Speed vs llama.cpp

### ISSUE THREAD

**Issue by aahouzi** [intel/neural-speed#94]
### Current Behavior:

- Genereted a gguf model from llama2-7b using llama.cpp code, and inferencing it directly with Neural Speed gives this text, and as u can see it's low quality:

![image](https://github.com/intel/neural-speed/assets/112881240/d2395072-7934-48b9-b24e-4046ba20e9d1)

- While inference the exact same gguf file with llama.cpp gives me this text:

![image](https://github.com/intel/neural-speed/assets/112881240/58b5db35-3b68-47e5-9070-1155e8a0828e)

### Steps To Reproduce:

```
# Windows
## llama.cpp
main.exe -m ggml-model-q4_0.gguf -p "Building a website can be done in 10 simple steps:" -n 512 --no-mmap --ignore-eos
## Neural Speed
python scripts\inference.py --model_name llama2 -m ggml-model-q4_0.gguf -n 512 -p "Building a website can be done in 10 simple steps:"
```

### Environment:

- **OS:**  Win11
- **HW:** SPR w9-3595X E5 128GB

**Comment by bearn01d** [comment]
Maybe related due to same setup: Phi-2 converted to f32 works probably fine, int4 produces garbage output, with compute_dtype int8 and group size -1 (Ubuntu 22.04, Raptor Lake notebook).

**Comment by bearn01d** [comment]
I don't think that the quantization is the problem, too. Because in my case it's GGUF as well (converted and quantized).

**Comment by kunger97** [comment]
> Maybe related due to same setup: Phi-2 converted to f32 works probably fine, int4 produces garbage output, with compute_dtype int8 and group size -1 (Ubuntu 22.04, Raptor Lake notebook).

i think you may open a new issue because use when i use quantization param `group size -1 ` also cause bad output

**Comment by Zhenzhong1** [comment]
@aahouzi Hi, please try transformer-based APIs by using this script scripts/python_api_example_for_gguf.py. 

Example in this PR: https://github.com/intel/neural-speed/pull/48.

I have double-chekced it. The low quality text issue will not happen again if you use this script.

**Comment by Zhenzhong1** [comment]
Hi, I closed this issue. Feel free to ask if you have any questions.
