### ISSUE TITLE
[Feature request] Add nllb support

### ISSUE THREAD

**Issue by bil-ash** [intel/neural-speed#99]
Please add nllb inference support. This(gguf inference for nllb) is already implemented elsewhere (acording to the documentation at https://github.com/facebookresearch/seamless_communication/tree/main/ggml#t2tt )and so I guess will not require too much effort

**Comment by Zhenzhong1** [comment]
@bil-ash Hi~Thanks for your issue. We have noticed this model. 

We'll take it into account in our plan. Thanks again.

**Comment by bil-ash** [comment]
Fine,looking forward to the support for nllb

**Comment by Zhenzhong1** [comment]
I closed this issue. I'll let you know if we enable the NLLB model.
